Repository HYF-Class20/agile-development-group1-hyf-redesign, pull requests merged in 2023-04, with the labels that each got.

#12 creat Communication file
  planning/communication.md
Labels: documentation

#10 create constraints
  planning/constraints.md
Labels: documentation

#8 create Readme file
  README.md
  planning/README.md
Labels: documentation, md

#4 create Backloge
  planning/backlog.md
Labels: documentation

#15 create development-strategy
  planning/development-strategy.md
Labels: documentation

#18 wireframe added and design.md edited
  planning/assets/homepage.jpg
  planning/design.md
Labels: md, wireframe, planning/design

#30 Coding footer responsive
  index.html
  public/assets/images/map.jpg
  styles/index.css
  styles/main.css
  styles/responsive.css
Labels: html, css

#32 header responsive
  index.html
  package-lock.json
  package.json
  public/assets/images/icon-close.svg
  public/assets/images/icon-menu.svg
  styles/assets/logo.svg
  styles/index.css
  styles/responsive.css
Labels: html, css

#34 coding banner
  index.html
  public/assets/images/banner.jpeg
  styles/footer.css
  styles/global.css
  styles/header.css
  styles/index.css
  styles/main.css
  styles/responsive.css
Labels: html, css
